---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    collection-file: requirements.yml

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../group_vars/
    group_vars:
      default_group:

verifier:
  name: ansible

driver:
  name: docker

platforms:
  - name: {{ cookiecutter.role_name }}-instance
    image: "${MOLECULE_DISTRO:-debian:stretch}"
    command: ${MOLECULE_DOCKER_COMMAND:-'bash -c "while true; do sleep 10000; done"'}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - default_group
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]
    apt_proxy_server: "${APT_PROXY_SERVER}"
    dns_search: "${DNS_SEARCH}"
